image: Visual Studio 2017
configuration: Release

install:
  - cd C:\projects\freecad
  - appveyor DownloadFile https://github.com/FreeCAD/FreeCAD-ports-cache/releases/download/v0.17/FreeCADLibs_11.5.1_x64_VC12.7z
  - powershell -Command 7z x FreeCADLibs_11.5.1_x64_VC12.7z > nul &&
      ren FreeCADLibs_11.5_x64_VC12 FreeCADLibs)
  - dir

before_build:
  - cd C:\projects\freecad
  - mkdir build & cd build
  - cmake .. -A x64 -DFREECAD_LIBPACK_DIR=C:\projects\freecad\FreeCADLibs -DBUILD_FEM_NETGEN=OFF

build:
  project: build/FreeCAD_Trunk.sln

after_build:
  - cd bin\Release\
  - FreeCADCmd.exe --run-test 0

artifacts:
  - path: build\bin\Release\*FreeCAD*.exe
    name: $(APPVEYOR_PROJECT_NAME)
